---
- name: Gather glance facts
  hosts: "freezer_all"
  gather_facts: "{{ osa_gather_facts | default(True) }}"
  tasks:
    - name: Gather additional facts
      include_role:
        name: openstack.osa.gather_extra_facts
      when: osa_gather_facts | default(True)
  tags:
    - always

- name: Configure haproxy services
  import_playbook: openstack.osa.haproxy_service_config
  vars:
    service_group: freezer_api
    service_variable: "freezer_haproxy_services"
  when:
    - groups[service_group] | length > 0
    - groups['haproxy'] | length > 0
  tags:
    - haproxy-service-config

- name: Install freezer services
  hosts: freezer_all
  gather_facts: false
  serial: "{{ freezer_api_serial | default(['1','100%']) }}"
  user: root
  environment: "{{ deployment_environment_variables | default({}) }}"
  tags:
    - freezer
  pre_tasks:
    - name: Setup installation variables
      include_role:
        name: openstack.osa.install_defaults
        defaults_from: "{{ install_method }}"
        public: true
        apply:
          tags:
            - always
      tags:
        - always

    # In order to ensure that any container, software or
    # config file changes which causes a container/service
    # restart do not cause an unexpected outage, we drain
    # the load balancer back end for this container.
    - name: Disabling haproxy backends
      include_role:
        name: openstack.osa.haproxy_endpoint_manage
        apply:
          tags:
            - always
      vars:
        haproxy_backend: freezer_api-back
        haproxy_state: disabled
      when:
        - "'freezer_api' in group_names"
        - "groups['freezer_api'] | length > 1"
      tags:
        - always

    - name: Including unbound-clients tasks
      include_role:
        name: openstack.osa.unbound_clients
      when:
        - hostvars['localhost']['resolvconf_enabled'] | bool

  roles:
    - role: "os_freezer"

  post_tasks:
    # Now that container changes are done, we can set
    # the load balancer back end for this container
    # to available again.
    - name: Enabling haproxy backends
      include_role:
        name: openstack.osa.haproxy_endpoint_manage
        apply:
          tags:
            - always
      vars:
        haproxy_backend: freezer_api-back
        haproxy_state: enabled
      when:
        - "'freezer_api' in group_names"
        - "groups['freezer_api'] | length > 1"
      tags:
        - always
